language: python

python:
  - "2.6"
  - "2.7"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux

sudo: false

install:
  # add brotli for tests
  - pip install brotlipy
  - python setup.py install
  - pip install coverage pytest-cov coveralls

script:
  - python setup.py test

after_success:
  - coveralls

